apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    app: hello-world-js
    version: v1
  name: hello-world-js
  namespace: default

spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: hello-world-js
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-js
        version: v1
    spec:
      containers:
      - image: server-3:5000/hello-world-js:latest
        imagePullPolicy: Always
        name: hello-world-js
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-js
  name: hello-world-js
  namespace: default
spec:
  ports:
  - nodePort: 30163
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello-world-js
    version: v1
  sessionAffinity: None
  type: NodePort